apiVersion: v1
kind: Pod
metadata:
  name: uba-accounts-pod
  labels:
    component: ubaAccounts
spec:
  containers:
    - name: uba-accounts
      image: sujits259/uba-accounts:1.3-docker
      ports:
        - containerPort: 9001
  imagePullSecrets:
    - name: dockerhubcredentials
