apiVersion: v1
kind: Service
metadata:
  name: uba-accounts-node-port
spec:
  type: NodePort
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 31001
  selector:
    component: ubaAccounts