version: "3.8"

services:
  mysqldb:
    image: mysql:8-oracle
    container_name: mysql-db-8
    restart: always
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQLDB_USER_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - uba-net
    volumes:
      - uba-data-volume:/var/lib/mysql
      - ./uba-data-volume/init.sql:/docker-entrypoint-initdb.d/init.sql

  uba-accounts:
    depends_on:
      - mysqldb
    image: sujits259/uba-accounts:1.0
    container_name: uba-accounts-1.0
    ports:
      - $UBA_ACCOUNTS_LOCAL_PORT:$UBA_ACCOUNTS_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_USER_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    networks:
      - uba-net
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  uba-data-volume:

networks:
  uba-net: