version: '3.8'
services:
  mysqldb:
    image: mysql:8-oracle
    container_name: mysql-db-8
    env_file: ./.envpodman
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQLDB_USER_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - uba-net-p
    volumes:
      - uba-data-volume-p:/var/lib/mysql
      - ./uba-data-volume-p/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  uba-data-volume-p:
    driver: local

networks:
  uba-net-p: