apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb
data:
  initdb.sql: |-
    CREATE DATABASE IF NOT EXISTS uba-db;
    USE uba-db;
    CREATE USER 'uba-db-user'@'10.244.0.36' IDENTIFIED BY 'mysecret';
    GRANT ALL PRIVILEGES ON *.* TO 'uba-db-user'@'10.244.0.36';
